// Generated by CoffeeScript 1.3.3
(function() {
  var liveServer, program, server, watch;

  liveServer = require('./server');

  watch = require('./watch');

  program = require('commander');

  server = null;

  exports.wacth = watch;

  exports.createServer = function(options) {
    var key, opts, value;
    if (server) {
      return server;
    }
    opts = {
      apiVersion: '1.6',
      host: '0.0.0.0',
      port: '35729'
    };
    for (key in options) {
      value = options[key];
      opts[key] = value;
    }
    server = new liveServer(opts);
    if (!options.path) {
      options.path = process.cwd();
    }
    watch.watch(options.path, options, function(event) {
      event.on('error', function(error) {
        return console.log(error);
      });
      return event.on('change', function(file) {
        if (server) {
          return sever.reloadBrowser([file]);
        }
      });
    });
    return server;
  };

  exports.stop = function() {
    if (server) {
      return server.stop();
    }
  };

  exports.cli = function(argv) {
    var list;
    list = function(val) {
      return val.split(',');
    };
    program.version('0.1.0').option('-p, --path [path]', 'Watch path. Default is current directory', String).option('-e, --exts [items]', 'File extentions list split by comma', list).parse(argv);
    if (!program.exts) {
      program.exts = watch.extentions;
    } else {
      program.exts = program.exts.concat(watch.extentions);
    }
    return exports.createServer(program);
  };

}).call(this);
